version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    networks:
      - clean-arch

  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    networks:
      - clean-arch

  database:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_USERNAME=root
      - MYSQL_DATABASE=clean_architecture
    networks:
      - clean-arch

networks:
  clean-arch:
    driver: bridge
